version: "3.8"

services:
  bookdarr:
    image: ghcr.io/thashiznit2003/bookdarr:latest
    container_name: bookdarr
    ports:
      - "8787:8787"
    environment:
      - PUID=1000
      - PGID=1000
      - BOOKDARR_CHOWN_BOOKS=1
      - BOOKDARR_CHOWN_DOWNLOADS=1
      - TZ=UTC
    volumes:
      - /opt/bookdarr/config:/config
      - /opt/bookdarr/books:/books
      - /qb1/downloads:/downloads
    restart: unless-stopped
