// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'addImportListExclusion': string;
  'actions': string;
  'foreignId': string;
  'importListExclusionsHeader': string;
  'name': string;
  'select': string;
}
export const cssExports: CssExports;
export default cssExports;
