// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addRootFolder': string;
  'addRootFolderHelp': string;
  'addRootFolderRow': string;
  'center': string;
  'rootFolders': string;
}
export const cssExports: CssExports;
export default cssExports;
