// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'sidebar': string;
  'sidebarContainer': string;
  'sidebarFooter': string;
  'sidebarFooterError': string;
  'sidebarFooterMessage': string;
  'sidebarFooterNote': string;
  'sidebarFooterStatus': string;
  'sidebarFooterTitle': string;
  'sidebarThrottleMessage': string;
  'sidebarThrottleNotification': string;
  'sidebarThrottleTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
